name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build Multi-platform Binaries
        run: |
          # macOS
          GOOS=darwin GOARCH=arm64 go build -o clash-speedtest-darwin-arm64 main.go
          GOOS=darwin GOARCH=amd64 go build -o clash-speedtest-darwin-x86_64 main.go
          
          # Linux
          GOOS=linux GOARCH=arm64 go build -o clash-speedtest-linux-arm64 main.go
          GOOS=linux GOARCH=386 go build -o clash-speedtest-linux-i386 main.go
          GOOS=linux GOARCH=amd64 go build -o clash-speedtest-linux-x86_64 main.go
          
          # Windows
          GOOS=windows GOARCH=arm64 go build -o clash-speedtest-windows-arm64.exe main.go
          GOOS=windows GOARCH=386 go build -o clash-speedtest-windows-i386.exe main.go
          GOOS=windows GOARCH=amd64 go build -o clash-speedtest-windows-x86_64.exe main.go
          
          # Create checksums
          sha256sum clash-speedtest-* > checksums.txt
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            clash-speedtest-darwin-arm64
            clash-speedtest-darwin-x86_64
            clash-speedtest-linux-arm64
            clash-speedtest-linux-i386
            clash-speedtest-linux-x86_64
            clash-speedtest-windows-arm64.exe
            clash-speedtest-windows-i386.exe
            clash-speedtest-windows-x86_64.exe
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
